//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "kill_switch")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub guild_id: String,
	pub ai_module: bool,
	pub anilist_module: bool,
	pub game_module: bool,
	pub anime_module: bool,
	pub vn_module: bool,
	pub updated_at: DateTime,
	#[sea_orm(column_name = "LevelModule")]
	pub level_module: bool,
	#[sea_orm(column_name = "MiniGameModule")]
	pub mini_game_module: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
