pub mod anime;
pub mod character;
pub mod compare;
pub mod level;
pub mod ln;
pub mod manga;
pub mod random;
pub mod register;
pub mod search;
pub mod staff;
pub mod studio;
pub mod user;
pub mod waifu;
// pub mod get_register_user;
// pub mod register_waifu;
