[bot]
discord_token = ""
bot_activity = "Let you get info from anilist."
remove_old_commands = false
respect_premium = true

[api]
enabled = true
port = 8080
api_key = "your_secure_api_key_here"

[music]
lavalink_hostname = ""
lavalink_password = ""

[db]
db_type = "postgresql"
host = ""
port = 1
user = ""
password = ""
database = ""

[image]
save_image = "false"
save_server = ""
token = ""

[logging]
log_level = "trace"
max_log_retention = 30

[ai]
ai_token = ""
ai_base_url = ""

[ai.image]
ai_image_token = ""
ai_image_base_url = ""
ai_image_model = ""
ai_image_quality = ""
ai_image_size = ""
ai_image_style = ""

[ai.question]
ai_question_token = ""
ai_question_base_url = ""
ai_question_model = ""

[ai.transcription]
ai_transcription_token = ""
ai_transcription_base_url = ""
ai_transcription_model = ""
