//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "activity_data")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub anime_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub server_id: String,
    pub episode: String,
    pub webhook: String,
    pub name: String,
    pub image: String,
    pub delay: i32,
    pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelatedEntity)]
pub enum RelatedEntity {}
