pub mod convert_flavored_markdown;
pub mod create_normalise_embed;
pub mod get_guild_lang;
pub mod general_channel_info;
pub mod get_option;
pub mod make_anilist_cached_request;
pub mod trimer;
pub mod image_saver;
pub mod error_management;