//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"activity_data"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub anime_id: i32,
	pub server_id: String,
	pub episode: i32,
	pub webhook: String,
	pub name: String,
	pub image: String,
	pub delay: i32,
	pub timestamp: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	AnimeId,
	ServerId,
	Episode,
	Webhook,
	Name,
	Image,
	Delay,
	Timestamp,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	AnimeId,
	ServerId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = (i32, String);
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	GuildData,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::AnimeId => ColumnType::Integer.def(),
			Self::ServerId => ColumnType::String(StringLen::None).def(),
			Self::Episode => ColumnType::Integer.def(),
			Self::Webhook => ColumnType::String(StringLen::None).def(),
			Self::Name => ColumnType::String(StringLen::None).def(),
			Self::Image => ColumnType::String(StringLen::None).def(),
			Self::Delay => ColumnType::Integer.def(),
			Self::Timestamp => ColumnType::DateTime.def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::GuildData => Entity::belongs_to(super::guild_data::Entity)
				.from(Column::ServerId)
				.to(super::guild_data::Column::GuildId)
				.into(),
		}
	}
}

impl Related<super::guild_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::GuildData.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
