//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"anime_song"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub anilist_id: String,
	pub ann_id: String,
	pub ann_song_id: String,
	pub anime_en_name: String,
	pub anime_jp_name: String,
	pub anime_alt_name: String,
	pub song_type: String,
	pub song_name: String,
	pub hq: String,
	pub mq: String,
	pub audio: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	AnilistId,
	AnnId,
	AnnSongId,
	AnimeEnName,
	AnimeJpName,
	AnimeAltName,
	SongType,
	SongName,
	Hq,
	Mq,
	Audio,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	AnilistId,
	AnnId,
	AnnSongId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = (String, String, String);
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::AnilistId => ColumnType::String(StringLen::None).def(),
			Self::AnnId => ColumnType::String(StringLen::None).def(),
			Self::AnnSongId => ColumnType::String(StringLen::None).def(),
			Self::AnimeEnName => ColumnType::String(StringLen::None).def(),
			Self::AnimeJpName => ColumnType::String(StringLen::None).def(),
			Self::AnimeAltName => ColumnType::String(StringLen::None).def(),
			Self::SongType => ColumnType::String(StringLen::None).def(),
			Self::SongName => ColumnType::String(StringLen::None).def(),
			Self::Hq => ColumnType::String(StringLen::None).def(),
			Self::Mq => ColumnType::String(StringLen::None).def(),
			Self::Audio => ColumnType::String(StringLen::None).def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		panic!("No RelationDef")
	}
}

impl ActiveModelBehavior for ActiveModel {}
