//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"command_list"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub command_name: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	CommandName,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	CommandName,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = String;
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	CommandUsage,
	ServerUserRelation,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::CommandName => ColumnType::String(StringLen::None).def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::CommandUsage => Entity::has_many(super::command_usage::Entity).into(),
			Self::ServerUserRelation => {
				Entity::has_many(super::server_user_relation::Entity).into()
			},
		}
	}
}

impl Related<super::command_usage::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CommandUsage.def()
	}
}

impl Related<super::server_user_relation::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ServerUserRelation.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
