//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"guild_data"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub guild_id: String,
	pub guild_name: String,
	pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	GuildId,
	GuildName,
	UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	GuildId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = String;
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	ActivityData,
	GuildLang,
	ModuleActivation,
	ServerImage,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::GuildId => ColumnType::String(StringLen::None).def(),
			Self::GuildName => ColumnType::String(StringLen::None).def().unique(),
			Self::UpdatedAt => ColumnType::DateTime.def().unique(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::ActivityData => Entity::has_many(super::activity_data::Entity).into(),
			Self::GuildLang => Entity::has_one(super::guild_lang::Entity).into(),
			Self::ModuleActivation => Entity::has_one(super::module_activation::Entity).into(),
			Self::ServerImage => Entity::has_many(super::server_image::Entity).into(),
		}
	}
}

impl Related<super::activity_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ActivityData.def()
	}
}

impl Related<super::guild_lang::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::GuildLang.def()
	}
}

impl Related<super::module_activation::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ModuleActivation.def()
	}
}

impl Related<super::server_image::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ServerImage.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
