//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"guild_lang"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub guild_id: String,
	pub lang: String,
	pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	GuildId,
	Lang,
	UpdatedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	GuildId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = String;
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	GuildData,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::GuildId => ColumnType::String(StringLen::None).def(),
			Self::Lang => ColumnType::String(StringLen::None).def(),
			Self::UpdatedAt => ColumnType::DateTime.def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::GuildData => Entity::belongs_to(super::guild_data::Entity)
				.from(Column::GuildId)
				.to(super::guild_data::Column::GuildId)
				.into(),
		}
	}
}

impl Related<super::guild_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::GuildData.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
