//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"guild_subscription"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub guild_id: String,
	pub entitlement_id: String,
	pub sku_id: String,
	pub created_at: DateTime,
	pub updated_at: DateTime,
	pub expired_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	GuildId,
	EntitlementId,
	SkuId,
	CreatedAt,
	UpdatedAt,
	ExpiredAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	GuildId,
	SkuId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = (String, String);
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	UserData,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::GuildId => ColumnType::String(StringLen::None).def().unique(),
			Self::EntitlementId => ColumnType::String(StringLen::None).def(),
			Self::SkuId => ColumnType::String(StringLen::None).def().unique(),
			Self::CreatedAt => ColumnType::DateTime.def(),
			Self::UpdatedAt => ColumnType::DateTime.def(),
			Self::ExpiredAt => ColumnType::DateTime.def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::UserData => Entity::belongs_to(super::user_data::Entity)
				.from(Column::GuildId)
				.to(super::user_data::Column::UserId)
				.into(),
		}
	}
}

impl Related<super::user_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserData.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
