//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"kill_switch"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub guild_id: String,
	pub ai_module: bool,
	pub anilist_module: bool,
	pub game_module: bool,
	pub anime_module: bool,
	pub vn_module: bool,
	pub updated_at: DateTime,
	pub level_module: bool,
	pub mini_game_module: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	GuildId,
	AiModule,
	AnilistModule,
	GameModule,
	AnimeModule,
	VnModule,
	UpdatedAt,
	#[sea_orm(column_name = "LevelModule")]
	LevelModule,
	#[sea_orm(column_name = "MiniGameModule")]
	MiniGameModule,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	GuildId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = String;
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::GuildId => ColumnType::String(StringLen::None).def(),
			Self::AiModule => ColumnType::Boolean.def(),
			Self::AnilistModule => ColumnType::Boolean.def(),
			Self::GameModule => ColumnType::Boolean.def(),
			Self::AnimeModule => ColumnType::Boolean.def(),
			Self::VnModule => ColumnType::Boolean.def(),
			Self::UpdatedAt => ColumnType::DateTime.def(),
			Self::LevelModule => ColumnType::Boolean.def(),
			Self::MiniGameModule => ColumnType::Boolean.def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		panic!("No RelationDef")
	}
}

impl ActiveModelBehavior for ActiveModel {}
