//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod activity_data;
pub mod anime_song;
pub mod command_list;
pub mod command_usage;
pub mod guild_data;
pub mod guild_lang;
pub mod guild_subscription;
pub mod kill_switch;
pub mod module_activation;
pub mod ping_history;
pub mod random_stats;
pub mod registered_user;
pub mod server_image;
pub mod server_user_relation;
pub mod user_color;
pub mod user_data;
pub mod user_subscription;
