//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"server_user_relation"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub user_id: String,
	pub guild_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	UserId,
	GuildId,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	UserId,
	GuildId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = (String, String);
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	CommandList,
	UserData,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::UserId => ColumnType::String(StringLen::None).def(),
			Self::GuildId => ColumnType::String(StringLen::None).def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::CommandList => Entity::belongs_to(super::command_list::Entity)
				.from((
					Column::GuildId,
					Column::GuildId,
					Column::GuildId,
					Column::GuildId,
				))
				.to((
					super::command_list::Column::CommandName,
					super::command_list::Column::CommandName,
				))
				.into(),
			Self::UserData => Entity::belongs_to(super::user_data::Entity)
				.from(Column::UserId)
				.to(super::user_data::Column::UserId)
				.into(),
		}
	}
}

impl Related<super::command_list::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CommandList.def()
	}
}

impl Related<super::user_data::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserData.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
