//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.13

use sea_orm::entity::prelude::*;

#[derive(Copy, Clone, Default, Debug, DeriveEntity)]
pub struct Entity;

impl EntityName for Entity {
	fn table_name(&self) -> &str {
		"user_data"
	}
}

#[derive(Clone, Debug, PartialEq, DeriveModel, DeriveActiveModel, Eq)]
pub struct Model {
	pub user_id: String,
	pub username: String,
	pub is_bot: bool,
	pub banner: String,
	pub added_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveColumn)]
pub enum Column {
	UserId,
	Username,
	IsBot,
	Banner,
	AddedAt,
}

#[derive(Copy, Clone, Debug, EnumIter, DerivePrimaryKey)]
pub enum PrimaryKey {
	UserId,
}

impl PrimaryKeyTrait for PrimaryKey {
	type ValueType = String;
	fn auto_increment() -> bool {
		false
	}
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {
	CommandUsage,
	GuildSubscription,
	Message,
	RegisteredUser,
	ServerUserRelation,
	UserColor,
	UserSubscription,
	Vocal,
}

impl ColumnTrait for Column {
	type EntityName = Entity;
	fn def(&self) -> ColumnDef {
		match self {
			Self::UserId => ColumnType::String(StringLen::None).def(),
			Self::Username => ColumnType::String(StringLen::None).def(),
			Self::IsBot => ColumnType::Boolean.def(),
			Self::Banner => ColumnType::String(StringLen::None).def(),
			Self::AddedAt => ColumnType::DateTime.def(),
		}
	}
}

impl RelationTrait for Relation {
	fn def(&self) -> RelationDef {
		match self {
			Self::CommandUsage => Entity::has_many(super::command_usage::Entity).into(),
			Self::GuildSubscription => Entity::has_one(super::guild_subscription::Entity).into(),
			Self::Message => Entity::has_many(super::message::Entity).into(),
			Self::RegisteredUser => Entity::has_one(super::registered_user::Entity).into(),
			Self::ServerUserRelation => {
				Entity::has_many(super::server_user_relation::Entity).into()
			},
			Self::UserColor => Entity::has_one(super::user_color::Entity).into(),
			Self::UserSubscription => Entity::has_one(super::user_subscription::Entity).into(),
			Self::Vocal => Entity::has_many(super::vocal::Entity).into(),
		}
	}
}

impl Related<super::command_usage::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::CommandUsage.def()
	}
}

impl Related<super::guild_subscription::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::GuildSubscription.def()
	}
}

impl Related<super::message::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Message.def()
	}
}

impl Related<super::registered_user::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::RegisteredUser.def()
	}
}

impl Related<super::server_user_relation::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::ServerUserRelation.def()
	}
}

impl Related<super::user_color::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserColor.def()
	}
}

impl Related<super::user_subscription::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::UserSubscription.def()
	}
}

impl Related<super::vocal::Entity> for Entity {
	fn to() -> RelationDef {
		Relation::Vocal.def()
	}
}

impl ActiveModelBehavior for ActiveModel {}
