pub mod admin;
pub mod ai;
pub mod anilist_server;
pub mod anilist_user;
pub mod anime;
pub mod anime_nsfw;
pub mod bot;
pub mod common;
pub mod game;
pub mod management;
pub mod new_member;
pub mod removed_member;
pub mod server;
pub mod user;
pub mod vn;
mod audio;
