use std::error::Error;
use std::fs;

fn main() -> Result<(), Box<dyn Error>> {
	cynic_codegen::register_schema("anilist")
		.from_sdl_file("schemas/anilist.graphql")?
		.as_default()?;
	generate_cron_task_launcher()?;
	Ok(())
}

fn generate_cron_task_launcher() -> Result<(), Box<dyn Error>> {
	// list all file inside the folder src/task/cron_task
	let all_file = fs::read_dir("src/task/cron_task")?;
	let mut import = String::new();
	let mut run = String::new();
	for file in all_file {
		let file = file?;
		if file.path().extension().unwrap() == "rs" {
			import.push_str(&format!(
				"use crate::task::cron_task::{};\n",
				file.file_name().to_str().unwrap()
			));
			run.push_str(&format!(
				r#"
    // launch a thread
    let cloned_bot_data = bot_data.clone();
    thread::spawn(move ||
            {}::exec(bot_data);\n
            ):
"#,
				file.file_name().to_str().unwrap()
			));
		}
	}
	let content = format!(
		r#"
 // file generated by build.rs
{}

pub fn run_all_cron_task(bot_data: Arc<BotData>) {{
    {}
}}
"#,
		import, run
	);
	Ok(())
}
