[package]
name = "kasuki"
version = "3.0.2"
edition = "2021"
authors = ["Valgul <contact@valgul.moe>"]
description = "A discord bot written in rust that get info from anilist API"
readme = "../readme.md"
repository = "https://github.com/ValgulNecron/kasuki"
license-file = "../LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["json", "multipart", "blocking"] }
serde = "1.0.217"
serde_json = "1.0.138"
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "next", default-features = false, features = ["gateway", "rustls_backend", "model", "utils", "full", "voice", "cache", "http", "unstable"] }
tokio = { version = "1.43.0", features = ["full"] }
rand = "0.9.0"
chrono = "0.4.39"
uuid = { version = "1.13.1", features = ["v4"] }
image = "0.25.5"
base64 = "0.22.1"
tracing = { version = "0.1.41" }
once_cell = "1.20.3 "
tracing-subscriber = { version = "0.3.19", features = ["default", "env-filter"] }
serde_with = { version = "3.12.0", features = ["macros"] }
rust-fuzzy-search = "0.1.1"
palette = "0.7.6"
tracing-appender = "0.2.3"
rayon = "1.10.0"
prost = "0.13.5"
markdown_converter = "0.3.4"
futures = "0.3.31"
rapidfuzz = "0.5.0"
cynic = { version = "3.10.0", features = ["reqwest", "http-reqwest", "serde_json"] }
moka = { version = "0.12.10", features = ["future"] }
toml = "0.8.20"
num-bigint = "0.4.6"
songbird = { git = "https://github.com/serenity-rs/songbird.git", branch = "serenity-next", features = ["serenity", "rustls", "builtin-queue", "gateway", "receive", "driver"] }
symphonia = { features = ["aac", "mp3", "isomp4", "alac", "symphonia-format-isomp4"], version = "0.5.4" }
dashmap = "7.0.0-rc0"
sea-orm = { version = "1.1.4", features = ["sqlx-sqlite", "sqlx-postgres", "runtime-tokio-rustls"] }
serde_urlencoded = "0.7.1"
catbox = "0.8.2"
tempfile = "3.16.0"
rusty_ytdl = { git = "https://github.com/Mithronn/rusty_ytdl.git", branch = "main", features = ["rustls-tls"] }
anyhow = "1.0.95"
small-fixed-array = "0.4.7"

[build-dependencies]
cynic-codegen = { version = "3.9.1" }

[profile.dev]
debug = 2

[profile.release]
lto = true
strip = true
opt-level = "s"
panic = "abort"
codegen-units = 1

[[bin]]
name = "kasuki"
path = "src/main.rs"
