//! A command structure to handle the "Question" functionality in the bot.
//!
//! The `QuestionCommand` struct implements the `Command` trait and is used to process
//! a specific command interaction where the user asks a question to an AI-based service.
//!
//! # Fields
//! - `ctx` - The Serenity context for the bot containing necessary data and utilities.
//! - `command_interaction` - The interaction data from the user, including input options.
//! - `command_name` - The name of the command invoked by the user.
//!
//! # See Also
//! - [`Command`](crate::command::command::Command): The trait this struct implements.

use crate::command::command::CommandRun;
use crate::command::embed_content::{CommandType, EmbedContent, EmbedsContents};
use crate::command::prenium_command::{PremiumCommand, PremiumCommandType};
use crate::constant::DEFAULT_STRING;
use crate::event_handler::BotData;
use crate::helper::get_option::subcommand::get_option_map_string_subcommand;
use anyhow::{anyhow, Result};
use fluent_templates::Loader;
use kasuki_macros::slash_command;
use reqwest::header::{HeaderMap, HeaderValue, AUTHORIZATION, CONTENT_TYPE};
use reqwest::Client;
use serde_json::{json, Value};
use serenity::all::{CommandInteraction, Context as SerenityContext};
use shared::helper::get_guild_lang::get_guild_language;
use shared::localization::USABLE_LOCALES;
use std::str::FromStr;
use std::sync::Arc;
use tracing::trace;
use unic_langid::LanguageIdentifier;

#[slash_command(
	name = "question", desc = "Ask a question and get the response (this is not a chat it has no context).",
	command_type = SubCommand(parent = "ai"),
	contexts = [Guild, BotDm, PrivateChannel],
	install_contexts = [Guild, User],
	extra_fields = [command_name: String = full_command_name.to_string()],
	args = [
		(name = "prompt", desc = "What you want to ask.", arg_type = String, required = true, autocomplete = false)
	],
)]
async fn question_command(self_: QuestionCommand) -> Result<EmbedsContents<'_>> {
	let ctx = self_.get_ctx();
	let command_interaction = self_.get_command_interaction();
	let bot_data = ctx.data::<BotData>().clone();
	let config = bot_data.config.clone();

	let guild_id = match command_interaction.guild_id {
		Some(id) => id.to_string(),
		None => String::from("0"),
	};
	let lang = get_guild_language(guild_id, bot_data.db_connection.clone()).await;
	let lang_code = match lang.as_str() {
		"jp" => "ja",
		"en" => "en-US",
		other => other,
	};
	let lang_id = LanguageIdentifier::from_str(lang_code)
		.unwrap_or_else(|_| LanguageIdentifier::from_str("en-US").unwrap());

	if self_
		.check_hourly_limit(
			self_.command_name.clone(),
			&bot_data,
			PremiumCommandType::AIQuestion,
		)
		.await?
	{
		let error_msg = USABLE_LOCALES.lookup(&lang_id, "ai_question-hourly_limit");
		return Err(anyhow!(error_msg));
	}

	let map = get_option_map_string_subcommand(command_interaction);
	let prompt = map.get(&String::from("prompt")).unwrap_or(DEFAULT_STRING);
	self_.defer().await?;

	let api_key = config
		.ai
		.question
		.ai_question_token
		.clone()
		.unwrap_or_default();
	let api_base_url = config
		.ai
		.question
		.ai_question_base_url
		.clone()
		.unwrap_or_default();
	let model = config
		.ai
		.question
		.ai_question_model
		.clone()
		.unwrap_or_default();

	let text = question(
		prompt,
		api_key,
		api_base_url,
		model,
		bot_data.http_client.clone(),
	)
	.await?;

	let embed_content = EmbedContent::new(String::new()).description(text);

	let embed_contents = EmbedsContents::new(CommandType::Followup, vec![embed_content]);

	Ok(embed_contents)
}

///
/// Sends a text prompt to a specified OpenAI language model API and retrieves the model's response.
///
/// # Parameters
/// - `text`: A reference to the input string containing the user's query or prompt.
/// - `api_key`: A `String` containing the API key for authentication with the OpenAI API.
/// - `api_base_url`: A `String` specifying the base URL of the OpenAI API endpoint.
/// - `model`: A `String` defining the name of the model to be used for processing the input.
///
/// # Returns
/// - Returns a `Result<String, reqwest::Error>`:
///     - `Ok(String)`: The response content generated by the model, with newline escape sequences (`\n`) replaced by actual newlines.
///     - `Err(reqwest::Error)`: An error encountered during the API request or response handling.
///
/// # Errors
/// - Returns an error if:
///     - The `api_url` cannot be constructed properly.
///     - The HTTP request to the API fails (e.g., due to network issues or invalid API key).
///     - The JSON response cannot be parsed correctly or does not contain the expected structure.
///
/// # Example
/// ```rust
/// use your_module::question;
///
/// #[tokio::main]
/// async fn main() {
///     let response = question(
///         &"What is the capital of France?".to_string(),
///         "your_api_key".to_string(),
///         "https://api.openai.com/v1".to_string(),
///         "gpt-3.5-turbo".to_string(),
///     ).await;
///
///     match response {
///         Ok(answer) => println!("Model response: {}", answer),
///         Err(e) => eprintln!("Error: {}", e),
///     }
/// }
/// ```
///
/// # Notes
/// - The function uses the `reqwest` library for making HTTP requests.
/// - The `Authorization` header is used to authenticate the API call using a bearer token.
/// - The `model` parameter must match an available model on the OpenAI platform (e.g., `gpt-4`, `gpt-3.5-turbo`).
/// - The function assumes a specific JSON structure in the response from the API. If the API's structure changes, the code may need updates.
///
/// # Dependencies
/// - Ensure the following crates are added to your `Cargo.toml`:
/// ```toml
/// reqwest = { version = "0.11", features = ["json", "blocking"] }
/// serde_json = "1.0"
/// log = "0.4"
/// ```
async fn question(
	text: &String, api_key: String, api_base_url: String, model: String, http_client: Arc<Client>,
) -> Result<String> {
	let api_url = api_base_url.to_string();

	let api_url = question_api_url(api_url);

	let client = http_client.clone();

	let mut headers = HeaderMap::new();

	headers.insert(
		AUTHORIZATION,
		HeaderValue::from_str(&format!("Bearer {}", api_key))?,
	);

	headers.insert(CONTENT_TYPE, HeaderValue::from_static("application/json"));

	let data = json!({
		 "model": model,
		 "messages": [{"role": "system", "content": "You are a helpful assistant."},{"role": "user", "content": text}]
	});

	trace!("{:?}", data);

	let res: Value = client
		.post(api_url)
		.headers(headers)
		.json(&data)
		.send()
		.await?
		.json()
		.await?;

	trace!("{:?}", res);

	let content = res["choices"][0]["message"]["content"].to_string();

	let content = content[1..content.len() - 1].to_string();

	Ok(content.replace("\\n", " \n "))
}

/// Constructs the URL for the OpenAI question API endpoint based on a given base URL.
///
/// # Arguments
///
/// * `api_url` - A `String` containing the base API URL supplied by the user.
///
/// # Returns
///
/// A `String` representing the complete URL to the OpenAI `chat/completions` endpoint.
///
/// # Logic
///
/// - If the provided `api_url` ends with `v1/`, the function appends `chat/completions` to it directly.
/// - If the provided `api_url` ends with `v1`, the function appends `/chat/completions` to it.
/// - If neither condition is met, the function appends `/v1/chat/completions` to the provided `api_url`.
///
/// # Examples
///
/// ```rust
/// let api_url1 = String::from("https://api.openai.com/v1/");
/// let api_url2 = String::from("https://api.openai.com/v1");
/// let api_url3 = String::from("https://api.openai.com");
///
/// assert_eq!(
///     question_api_url(api_url1),
///     "https://api.openai.com/v1/chat/completions"
/// );
/// assert_eq!(
///     question_api_url(api_url2),
///     "https://api.openai.com/v1/chat/completions"
/// );
/// assert_eq!(
///     question_api_url(api_url3),
///     "https://api.openai.com/v1/chat/completions"
/// );
/// ```
///
/// This function ensures the resulting URL always points to the `v1/chat/completions` endpoint,
/// minimizing user input errors in constructing the correct API URL.
pub fn question_api_url(api_url: String) -> String {
	if api_url.ends_with("v1/") {
		format!("{}chat/completions", api_url)
	} else if api_url.ends_with("v1") {
		format!("{}/chat/completions", api_url)
	} else {
		format!("{}/v1/chat/completions", api_url)
	}
}
