pub mod anilist_activity;
pub mod struct_anime_register;
pub mod struct_character_register;
pub mod struct_level_register;
pub mod struct_ln_register;
pub mod struct_manga_register;
pub mod struct_studio_register;
pub mod struct_user_register;
pub mod struct_waifu_register;
